In [7]:
import numpy as np
arr_ones = np.ones((2, 3, 4), dtype=np.int16)
print(arr_ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [8]:
arr_zeros = np.zeros(2)
print(arr_zeros)

[0. 0.]


In [ ]:
arr_empty = np.empty((2, 3))
print(arr_empty)

In [ ]:
arr = np.arange(4)
print(arr)

In [ ]:
arr = np.arange(2, 9, 2)
print(arr)

In [ ]:
arr = np.arange(0, 2, 0.3)
print(arr)

In [9]:
arr = np.linspace(0, 10, num=5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]
